name: Build pushoo-chan webpack

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run build:webpack
      - name: Upload to github artifact
        uses: NyaMisty/upload-artifact-as-is@master
        with:
          path: dist/bundle.js
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: dist/bundle.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

